### ISSUE TITLE
No module named 'ShaderNodesExtra2' on installation

### ISSUE THREAD

**Issue by trych** [Secrop/ShaderNodesExtra2.80#10]
Hi there!

I am having issues activating this addon. I can add it via "Install..." and picking the zip file, it also gets listed then, but when I try to check it to activate, I'm getting this error:

![20210828-232959_Screenshot_Blender](https://user-images.githubusercontent.com/9803905/131231525-0f734980-daaf-4b16-8824-47c091fb9370.png)

Any idea, what is going on? I also followed the advice to change the zip name to not contain any `-` or `.`, but it still does not work.

Thanks!

**Comment by ghost** [comment]
Hi, try unpacking addon, rename folder remove the trailing "2.80"

Pack the folder to zip

Install

**Comment by trych** [comment]
@iyadahmed Thanks a lot, now it works!

**Comment by Secrop** [comment]
Hi 'Trych',

Have you downloaded the 'Release' file or the Source as Zip?.. There's a
link in the right side of the github page..

The 'Source as Zip' contains a file structure naming that is not compatible
with python. The Github team knows this and never showed will to change it.
The solution is to unzip into a folder, rename the inner to 'ShaderNodes2'

check out this link instead and tell me if it works:
https://github.com/Secrop/ShaderNodesExtra2.80/releases/tag/0.2.0

Regards,
S

**Comment by trych** [comment]
@Secrop Thanks. Turns out, I actually did download the "Source code (zip)" link and that was not compatible. When I download directly from the link that you provided, it works.
