### ISSUE TITLE
abnormal duplication of nodetrees

### ISSUE THREAD

**Issue by Secrop** [Secrop/ShaderNodesExtra2.80#2]
Depsgraph calls the copy(self, node) everytime a prop is changed. This results in duplicated nodetrees. This call is not supposed to happen unless the node is being copied in the editor (and not in the COW routines). Right now, there's no way to distinguish if the second node is just a dummy from the depsgraph or a new node in the editor (otherwise this would be fairly simple to fix, without fixing it in blender's source)

**Comment by melMass** [comment]
This is now fixed !!
https://developer.blender.org/T62624

**Comment by Secrop** [comment]
Thanks @melMass; I've been so concentrated with fixing other things that I totally forgot to update this.. :)
