### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by kostex** [Secrop/ShaderNodesExtra2.80#7]
Hi, thanks for supplying the addons.

Is there any documentation/tutorial available on how to use the displacement baker?

Sorry for reporting this question as an issue..

**Comment by Secrop** [comment]
Hi kostex, sorry for the late reply. (i'm not receiving notifications from github)
I've talk about it a bit in BlenderArtists.org (don't recall which thread)..

But the process is a bit simple:
The first thing to have is the same UVmap in both hires and low res.
The best way to achieve this, is to unwrap your lowres, and use the Multiresolution modifier for creating and sculpting the hires object. This way the engine will know where each pixel in the lowres object will end in the hires object.

Then is just a few steps:
- add a Displacement_Bake node to the hires object, set it to 'Position', and bake the output to a Exr file. This will store the end coordinates into the file.
- on the lowres, also add a Displacement_Bake, and an ImageTextureNode with the baked Exr (non-color). - set the Displacement_Bake to 'Object Vector Displacement', connect the ImageTexture to the 'Position(High Resolution)' socket, and bake the output to another Exr file.
