### ISSUE TITLE
Can't figure out how to install it

### ISSUE THREAD

**Issue by Diplodocee** [Secrop/ShaderNodesExtra2.80#9]
Hello!
I've been trying to figure out how to install the addon (I'm using 2.80 on Windows) but haven't been able to get Blender to recognize it. Can you install it through User Preferences like any other addon, or is there something special you have to do?

**Comment by Diplodocee** [comment]
I can get the 2.7 version to install (it doesn't work, obviously, but it installs), but the 2.8 version won't show up as an addon.

**Comment by Secrop** [comment]
As pointed in the other [issue](https://github.com/Secrop/ShaderNodesExtra2.80/issues/6), you need to rename the folder name. Python don't like modules with "-" in their name, but Github insists in putting "-master" in there.

**Comment by Diplodocee** [comment]
Thank you!
